# version: '3.8'

services:

  info-gest:
    container_name: frontend_info-gest
    build:
      context: info-gest    
      target: development
    working_dir: /code
    ports:
      - "3000:3000"
    volumes:
      - ./info-gest:/code
      - /code/node_modules
    networks:
      info-gest:
        ipv4_address: 192.30.0.7
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    # env_file:
    #    - ./info-gest/.env

networks:
  info-gest:
    driver: bridge
    ipam:
      config:
        - subnet: 192.30.0.0/24